### PR TITLE
Dispute fee charged on parachain

### LINKED ISSUE #12: Dispute fee charged on parachain
As discussed on a recent call, the fees associated with beginning a dispute should be charged on the originating parachain rather than within the staking contract.

Addition:
Need to handle dispute fee cases also:
1. Return dispute fee to dispute_initiator if vote  result is Pass and Invalid
2. Transfer dispute fee to reporter if vote result is  Fail

### PR DESCRIPTION
**Pull request by pawanbisht62**
This PR resolves #12.

Changes:
1. Dispute fee is charged on the oracle consumer chain instead of sending fee to the contract.
2. Added functionality to handles dispute fee transaction(Slashing/Returning) in the execute_vote for all three cases (Pass/Invalid/Fail)

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -1217,11 +1219,15 @@ pub mod pallet {
...
-			// require(
-			// 	token.transferFrom(msg.sender, address(this), _disputeFee),
-			// 	"Fee must be paid"
-			// ); // This is the dispute fee. Returned if dispute passes
 			let dispute_fee = vote.fee;
+			// should we check for funds availability?
+			let pallet_id = T::PalletId::get();
+			T::Token::transfer(
+				&dispute_initiator,
+				&pallet_id.into_sub_account_truncating(b"dispute"),
```
Comment (evilrobot-01) [inline src/lib.rs:1227]: Would moving b"dispute" to constants.rs make sense, as the same value is being used across files?

File: src/impls.rs [hunk 2]
```diff
@@ -62,7 +62,28 @@ impl<T: Config> Pallet<T> {
 						disputes.saturating_dec();
 					}
 				});
-				vote.result = Some(result.clone());
+				vote.result = Some(result);
+
+				// handling transfer of dispute fee
+				let pallet_id = T::PalletId::get();
```
[the remark this answers is not in the document]
Comment (evilrobot-01) [reply src/impls.rs:68]: The only thing different between the two match arm bodies seems to be the beneficiary, so wonder if that can be a variable based on result?

If its about the same number of lines then probably not worth the effort tho...

```
let dest = match result { .. };
T::Token::transfer(
	&pallet_id.into_sub_account_truncating(b"dispute"),
	&dest,
	vote.fee,
	false,
).or(Err(Error::<T>::InsufficientBalance))?;
```

File: src/lib.rs [hunk 3]
```diff
@@ -530,6 +530,8 @@ pub mod pallet {
 		VoteNotTallied,
 		/// Time for voting has not elapsed.
 		VotingPeriodActive,
+		/// Balance must be greater than transferring amount
+		InsufficientBalance,
```
Comment (evilrobot-01) [inline src/lib.rs:534]: Do we need this? I would assume that the RuntimeError type from the Token:transfer() call would be bubble up? Perhaps the return type of the functions in impls.rs can be changed wherever used to negate the need for it.

File: src/tests/governance.rs [hunk 4]
```diff
@@ -58,6 +58,8 @@ fn begin_dispute() {
 		let dispute_id = with_block(|| {
 			// todo:
 			// await h.expectThrow(gov.connect(accounts[4]).beginDispute(ETH_QUERY_ID, blocky.timestamp)) // must have tokens to pay/begin dispute
```
Comment (evilrobot-01) [inline src/tests/governance.rs:60]: Can this todo commented out code now be removed?

File: src/tests/governance.rs [hunk 5]
```diff
@@ -85,6 +87,11 @@ fn begin_dispute() {
 			);
 			// todo
 			// assert(balance1 - balance2 - (await flex.getStakeAmount()/10) == 0, "dispute fee paid should be correct")
```
Comment (evilrobot-01) [inline src/tests/governance.rs:89]: Can we align with the Tellor implementation?

File: src/lib.rs (hunk 3 above)
Comment (pawanbisht62) [reply src/lib.rs:534]: I guess, yes we need, as From<pallet_balances::Error<T>>` is not implemented for `pallet::Error<T>`.

**Comment by pawanbisht62** [comment]
Hi @evilrobot-01 ,

I've addressed your review comments.

Please take a look when you get time.

Thanks

File: src/lib.rs (hunk 3 above)
Comment (evilrobot-01) [reply src/lib.rs:455]: https://github.com/tellor-io/tellor-pallet/pull/33 provides a suggested solution, if you are happy to merge into your PR.

File: src/tests/oracle.rs [hunk 6]
```diff
@@ -1607,6 +1609,125 @@ fn get_data_before() {
...
+
+	// Prerequisites
+	ext.execute_with(|| {
+		with_block(|| {
+			register_parachain(STAKE_AMOUNT);
+			super::deposit_stake(reporter, STAKE_AMOUNT, Address::random());
+		})
+	});
+
+	// Based on https://github.com/tellor-io/tellorFlex/blob/3b3820f2111ec2813cb51455ef68cf0955c51674/test/functionTests-TellorFlex.js#L127
```
Comment (evilrobot-01) [inline src/tests/oracle.rs:1627]: Invalid link, perhaps just remove the comment.

File: src/tests/oracle.rs [hunk 7]
```diff
@@ -1607,6 +1609,125 @@ fn get_data_before() {
...
+	let query_data: QueryDataOf<Test> = spot_price("dot", "usd").try_into().unwrap();
+	let query_id = keccak_256(query_data.as_ref()).into();
+	let reporter = 1;
+	let another_reporter = 2;
+	let mut ext = new_test_ext();
+
+	// Prerequisites
+	ext.execute_with(|| with_block(|| register_parachain(STAKE_AMOUNT)));
+
+	// Based on https://github.com/tellor-io/tellorFlex/blob/3b3820f2111ec2813cb51455ef68cf0955c51674/test/functionTests-TellorFlex.js#L127
```
Comment (evilrobot-01) [inline src/tests/oracle.rs:1667]: Invalid link, perhaps just remove the comment.

File: src/tests/oracle.rs [hunk 8]
```diff
@@ -1607,6 +1609,125 @@ fn get_data_before() {
 	});
 }
 
+#[test]
```
Comment (evilrobot-01) [inline src/tests/oracle.rs:1612]: These two tests relate to governance functionality, so could they be moved to `tests/governance.rs` please?

**Review by evilrobot-01 — CHANGES_REQUESTED** [review]
A few minor tweaks and moving two tests.

Thanks!

File: src/lib.rs [hunk 9]
```diff
@@ -1116,11 +1121,15 @@ pub mod pallet {
 			}
 			<VoteCount<T>>::mutate(|count| count.saturating_inc());
 			// todo: confirm dispute fee handling with Tellor
```
[the remark this answers is not in the document]
Comment (pawanbisht62) [reply src/lib.rs:1123]: Sure

**Comment by pawanbisht62** [comment]
> A few minor tweaks and moving two tests.
> 
> Thanks!

@evilrobot-01,  Thanks for the valuable feedback.
Incorporated all the suggestions

**Review by evilrobot-01 — APPROVED** [review]
LGTM, thanks!

File: src/impls.rs [hunk 10]
```diff
@@ -47,32 +48,44 @@ impl<T: Config> Pallet<T> {
...
+					vote.result = Some(result);
+
+					// handling transfer of dispute fee
+					let dispute_account =
+						&T::PalletId::get().into_sub_account_truncating(DISPUTE_SUB_ACCOUNT_ID);
+					let dest = match result {
+						VoteResult::Passed | VoteResult::Invalid => &vote.initiator,
+						VoteResult::Failed => &dispute.disputed_reporter,
+					};
+					T::Token::transfer(dispute_account, dest, vote.fee, false)?;
```
Comment (oraclown) [inline src/impls.rs:84]: Does this function only transfer the dispute fee for a single round, or for each round of voting? It looks like just a single round, but I could be missing it because I'm not super familiar with Rust. It should transfer it for each round of voting like [here](https://github.com/tellor-io/governance/blob/main/contracts/Governance.sol#L207).

Bumping [this issue](https://github.com/tellor-io/tellor-parachain-contracts/issues/14) as well. And the current `executeVote` logic on the contracts side [here](https://github.com/tellor-io/tellor-parachain-contracts/blob/main/src/ParachainGovernance.sol#L347).

**Review by oraclown — COMMENTED** [review]
Thanks for the updates @pawanbisht62

File: src/impls.rs (hunk 10 above)
Comment (pawanbisht62) [reply src/impls.rs:84]: Hi @oraclown,

As discussed, we'll be addressing this in the new issue, so is there anything else you want to highlight here?
Thanks

Comment (evilrobot-01) [reply src/impls.rs:84]: @pawanbisht62 We still need to add the iteration of the vote rounds in this PR to conclude please. The merging of the relevant dispatchable functions will be tackled in another PR and i will create an issue for it now.

Comment (oraclown) [reply src/impls.rs]: Nothing else from me. Thanks, @pawanbisht62 

I made that issue (which might need more detail) #36,  @evilrobot-01 . I didn't see an existing one, but feel free to close as duplicate if I missed it

**Comment by pawanbisht62** [comment]
Hi team,

Other changes like:
1. Remove vote_round field from the execute_vote()
2. Merging of report_slash, report_invalid_dispute & slash_dispute_initiator into a single function

Will be incorporated in separate PR.

cc: @oraclown @evilrobot-01
